# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('text', 'list')]),
        ),
    ]
